name: deploy_frontend

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Set Azure subscription
      run: |
        az account show
        az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    
    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
          ACCOUNT_KEY=$(az storage account keys list --account-name ${{ secrets.STORAGE_ACCOUNT_NAME }} --resource-group ${{ secrets.RESOURCE_GROUP_NAME }} --query '[0].value' -o tsv)
          az storage blob upload-batch --account-name ${{ secrets.STORAGE_ACCOUNT_NAME }} --account-key "$ACCOUNT_KEY" -d '$web' -s frontend/
    
    - name: Purge CDN endpoint
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az cdn endpoint purge --content-paths  "/*" --profile-name "${{ secrets.CDN_PROFILE_NAME }}" --name "${{ secrets.CDN_ENDPOINT_NAME }}" --resource-group "${{ secrets.RESOURCE_GROUP_NAME }}"
    
    # Azure logout
    - name: logout
      run: |
        az logout
      if: always()